config/routes.rb
Rails.application.routes.draw do
  resources :oenologists
  root 'wines#index'
  devise_for :friends
  
  resources :strains
  get '/wines/:id/add_new', to: 'wines#add_new', as: 'add_new'
  resources :wines

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/oenologist.rb
class Oenologist < ApplicationRecord
  has_and_belongs_to_many :wines
end

app/models/strain.rb
class Strain < ApplicationRecord
  has_many :wine_strains
  has_many :wines, through: :wine_strains, dependent: :destroy

  has_many :wine_scores
  has_many :oenologists, through: :wine_scores, dependent: :destroy

  validates :name, presence: true
  validates_uniqueness_of :name
end

app/models/wine.rb
class Wine < ApplicationRecord
  validates_presence_of :name
  
  has_many :wine_strains
  has_many :strains, through: :wine_strains, dependent: :destroy

  has_and_belongs_to_many :oenologists

  accepts_nested_attributes_for :wine_strains
end

app/models/wine_strain.rb
class WineStrain < ApplicationRecord
  belongs_to :wine
  belongs_to :strain

  validates_presence_of :percentage
  validates :wine_id, uniqueness: { scope: :strain_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_friend!
  before_action :is_admin?, only: %i[ new add_new create edit update destroy ]

  private
    def is_admin?
      if friend_signed_in?
        redirect_to root_path unless current_friend.admin
      end
    end
end

app/controllers/oenologists_controller.rb
class OenologistsController < ApplicationController
  before_action :set_oenologist, only: %i[ show edit update destroy ]

  # GET /oenologists or /oenologists.json
  def index
    @oenologists = Oenologist.all
  end

  # GET /oenologists/1 or /oenologists/1.json
  def show
  end

  # GET /oenologists/new
  def new
    @oenologist = Oenologist.new
  end

  # GET /oenologists/1/edit
  def edit
  end

  # POST /oenologists or /oenologists.json
  def create
    @oenologist = Oenologist.new(oenologist_params)

    respond_to do |format|
      if @oenologist.save
        format.html { redirect_to oenologist_url(@oenologist), notice: "Oenologist was successfully created." }
        format.json { render :show, status: :created, location: @oenologist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oenologists/1 or /oenologists/1.json
  def update
    respond_to do |format|
      if @oenologist.update(oenologist_params)
        format.html { redirect_to oenologist_url(@oenologist), notice: "Oenologist was successfully updated." }
        format.json { render :show, status: :ok, location: @oenologist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oenologists/1 or /oenologists/1.json
  def destroy
    @oenologist.destroy

    respond_to do |format|
      format.html { redirect_to oenologists_url, notice: "Oenologist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oenologist
      @oenologist = Oenologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def oenologist_params
      params.require(:oenologist).permit(:name, :age, :nationality, :work_place)
    end
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  before_action :set_strain, only: %i[ show edit update destroy ]

  # GET /strains or /strains.json
  def index
    @strains = Strain.all
  end

  # GET /strains/1 or /strains/1.json
  def show
  end

  # GET /strains/new
  def new
    @strain = Strain.new
  end

  # GET /strains/1/edit
  def edit
  end

  # POST /strains or /strains.json
  def create
    @strain = Strain.new(strain_params)

    respond_to do |format|
      if @strain.save
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully created." }
        format.json { render :show, status: :created, location: @strain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strains/1 or /strains/1.json
  def update
    respond_to do |format|
      if @strain.update(strain_params)
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully updated." }
        format.json { render :show, status: :ok, location: @strain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strains/1 or /strains/1.json
  def destroy
    @strain.destroy

    respond_to do |format|
      format.html { redirect_to strains_url, notice: "Strain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strain
      @strain = Strain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def strain_params
      params.require(:strain).permit(:name)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit add_new update destroy ]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @wine.wine_strains.build.build_strain
  end

  # GET /wines/1/edit
  def edit
  end
  
  def add_new
    @wine.wine_strains.build.build_strain
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy

    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      # params.require(:wine).permit(:name, wine_strains_attributes: [:id, :percentage, :strain_id])
      params.require(:wine).permit(:name, :score, wine_strains_attributes: [:id, :percentage, :strain_id], oenologist_ids: [] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oenologists_helper.rb
module OenologistsHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cepas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="friend_nav">
      <% if friend_signed_in? %>
        Signed in as <%= current_friend.email %>
        <%= link_to "Sign out", destroy_friend_session_path, :method => :delete %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/oenologists/_form.html.erb
<%= form_with(model: oenologist) do |form| %>
  <% if oenologist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oenologist.errors.count, "error") %> prohibited this oenologist from being saved:</h2>

      <ul>
        <% oenologist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality %>
  </div>

  <div class="field">
    <%= form.label :work_place %>
    <%= form.text_field :work_place %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/oenologists/edit.html.erb
<h1>Editing Oenologist</h1>

<%= render 'form', oenologist: @oenologist %>

<%= link_to 'Show', @oenologist %> |
<%= link_to 'Back', oenologists_path %>

app/views/oenologists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Oenologists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Nationality</th>
      <th>Work place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oenologists.each do |oenologist| %>
      <tr>
        <td><%= oenologist.name %></td>
        <td><%= oenologist.age %></td>
        <td><%= oenologist.nationality %></td>
        <td><%= oenologist.work_place %></td>
        <td><%= link_to 'Show', oenologist %></td>
        <td><%= link_to 'Edit', edit_oenologist_path(oenologist) %></td>
        <td><%= link_to 'Destroy', oenologist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oenologist', new_oenologist_path %>

app/views/oenologists/new.html.erb
<h1>New Oenologist</h1>

<%= render 'form', oenologist: @oenologist %>

<%= link_to 'Back', oenologists_path %>

app/views/oenologists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @oenologist.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @oenologist.age %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @oenologist.nationality %>
</p>

<p>
  <strong>Work place:</strong>
  <%= @oenologist.work_place %>
</p>

<%= link_to 'Edit', edit_oenologist_path(@oenologist) %> |
<%= link_to 'Back', oenologists_path %>

app/views/strains/_form.html.erb
<%= form_with(model: strain) do |form| %>
  <% if strain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(strain.errors.count, "error") %> prohibited this strain from being saved:</h2>

      <ul>
        <% strain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/strains/edit.html.erb
<h1>Editing Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Show', @strain %> |
<%= link_to 'Back', strains_path %>

app/views/strains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Strains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strains.each do |strain| %>
      <tr>
        <td><%= strain.name %></td>
        <td><%= link_to 'Show', strain %></td>
        <td><%= link_to 'Edit', edit_strain_path(strain) %></td>
        <td><%= link_to 'Destroy', strain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Strain', new_strain_path %>

app/views/strains/new.html.erb
<h1>New Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Back', strains_path %>

app/views/strains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @strain.name %>
</p>

<%= link_to 'Edit', edit_strain_path(@strain) %> |
<%= link_to 'Back', strains_path %>

app/views/wines/_form.html.erb
<%= form_with(model: wine) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.fields_for :wine_strains do |wine_strains_form| %>
    <div>
      <%= wine_strains_form.number_field :percentage, in: 0..100, step: 0.1 %>
      <%= wine_strains_form.collection_select(:strain_id, Strain.all, :id, :name, { :prompt => 'Selecciona una cepa' }) %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score, in: 0..100, step: 0.5 %>
  </div>

  <div class="field">
    <%= form.collection_check_boxes :oenologist_ids, Oenologist.all, :id, :name  do |b|%>
      <div>
        <%= b.label(:"data-value" => b.value) { b.check_box + b.text } %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/add_new.erb
<h1>Add New Strain</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>
<% @wines.each do |wine| %>

  <div>
    <span>
      <%= wine.name %>
    </span>
    <span>
      <span><%= link_to 'Show', wine %></span>
      <span><%= link_to 'Add', add_new_path(wine) %></span>
      <span><%= link_to 'Edit', edit_wine_path(wine) %></span>
      <span><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></span>
    </span>
  </div>

  <ul>
    <% wine.strains.order(:name).each do |ws| %>
      <li>
        <%= ws.name %> (<%= wine.wine_strains.find_by(strain_id: ws.id).percentage %>%)
      </li>
    <% end %>
  </ul>
<% end %>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<ul>
  <% @wine.strains.order(:name).each do |ws| %>
    <li>
      <%= ws.name %> (<%= @wine.wine_strains.find_by(strain_id: ws.id).percentage %>%)
    </li>
  <% end %>
</ul>

<%= link_to 'Add New', add_new_path(@wine) %>
<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>